<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Log;

/**
 * A screenshot for a page. This is generated by laravel dusk
 * and stored in laravel storage.
 *
 * An Eloquent Model: 'Screenshot'
 *
 * @property integer $id
 * @property string $uuid
 * @property integer $page_id
 * @property string $src
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property Carbon $deleted_at
 * @property-read Page $page
 *
 */
class Screenshot extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'uuid',
        'page_id',
        'src'
    ];


    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('user', function (Builder $builder) {
            $builder->whereIn('page_id', Page::pluck('id'));  //Pages are already user scoped
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function page()
    {
        return $this->belongsTo(Page::class);
    }
}
